print("Hello world")

# Generated by BM Agents.md
def sum_two_numbers(a, b):
    """
    Function to sum two numbers.
    
    Args:
        a (int/float): First number
        b (int/float): Second number
    
    Returns:
        int/float: Sum of the two numbers
    """
    return a + b

# Example usage
if __name__ == "__main__":
    result = sum_two_numbers(5, 3)
    print(f"Sum of 5 and 3 is: {result}")
    
    # You can also use it with different numbers
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = sum_two_numbers(num1, num2)
    print(f"Sum of {num1} and {num2} is: {result}")
