# name: On Main Branch Commit

# on:
#   push:
#     branches:
#       - main   # Trigger only when commits are pushed to main

# permissions:
#   contents: write       # allow pushing branches
#   pull-requests: write  # allow creating PRs

# jobs:
#   create-pr:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Create a new branch
#         run: |
#           BRANCH_NAME="auto-pr-$(date +%s)"
#           echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
#           git checkout -b $BRANCH_NAME
#           echo "Hello from GitHub Actions at $(date)" >> action-output.txt   # note timestamp
#           git config user.name "github-actions[bot]"
#           git config user.email "github-actions[bot]@users.noreply.github.com"
#           git add action-output.txt
#           git commit -m "Add action output $(date)"
#           git push origin $BRANCH_NAME

#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v5
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ env.BRANCH_NAME }}   # use the new branch
#           base: main                       # PR will target main
#           title: "Auto PR from workflow"
#           body: |
#             This PR was created automatically when something was pushed to main.
